//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Sweng500.Pml.DataAccessLayer", "CodeTypeCode", "CodeType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sweng500.Pml.DataAccessLayer.CodeType), "Code", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.Code), true)]
[assembly: EdmRelationshipAttribute("Sweng500.Pml.DataAccessLayer", "BorrowerBorrowedMedia", "Borrower", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sweng500.Pml.DataAccessLayer.Borrower), "BorrowedMedia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.BorrowedMedia), true)]
[assembly: EdmRelationshipAttribute("Sweng500.Pml.DataAccessLayer", "MediaBorrowedMedia", "Media", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sweng500.Pml.DataAccessLayer.Media), "BorrowedMedia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.BorrowedMedia), true)]
[assembly: EdmRelationshipAttribute("Sweng500.Pml.DataAccessLayer", "AuthorBook", "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.Author), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.Book))]
[assembly: EdmRelationshipAttribute("Sweng500.Pml.DataAccessLayer", "VideoProducer", "Video", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.Video), "Producer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.Producer))]
[assembly: EdmRelationshipAttribute("Sweng500.Pml.DataAccessLayer", "DirectorVideo", "Director", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.Director), "Video", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sweng500.Pml.DataAccessLayer.Video))]

#endregion

namespace Sweng500.Pml.DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MasterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MasterEntities object using the connection string found in the 'MasterEntities' section of the application configuration file.
        /// </summary>
        public MasterEntities() : base("name=MasterEntities", "MasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MasterEntities object.
        /// </summary>
        public MasterEntities(string connectionString) : base(connectionString, "MasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MasterEntities object.
        /// </summary>
        public MasterEntities(EntityConnection connection) : base(connection, "MasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CodeType> CodeTypes
        {
            get
            {
                if ((_CodeTypes == null))
                {
                    _CodeTypes = base.CreateObjectSet<CodeType>("CodeTypes");
                }
                return _CodeTypes;
            }
        }
        private ObjectSet<CodeType> _CodeTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Code> Codes
        {
            get
            {
                if ((_Codes == null))
                {
                    _Codes = base.CreateObjectSet<Code>("Codes");
                }
                return _Codes;
            }
        }
        private ObjectSet<Code> _Codes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Media> Media
        {
            get
            {
                if ((_Media == null))
                {
                    _Media = base.CreateObjectSet<Media>("Media");
                }
                return _Media;
            }
        }
        private ObjectSet<Media> _Media;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BorrowedMedia> BorrowedMedias
        {
            get
            {
                if ((_BorrowedMedias == null))
                {
                    _BorrowedMedias = base.CreateObjectSet<BorrowedMedia>("BorrowedMedias");
                }
                return _BorrowedMedias;
            }
        }
        private ObjectSet<BorrowedMedia> _BorrowedMedias;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CodeTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCodeTypes(CodeType codeType)
        {
            base.AddObject("CodeTypes", codeType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Codes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCodes(Code code)
        {
            base.AddObject("Codes", code);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Media EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedia(Media media)
        {
            base.AddObject("Media", media);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BorrowedMedias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBorrowedMedias(BorrowedMedia borrowedMedia)
        {
            base.AddObject("BorrowedMedias", borrowedMedia);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="personId">Initial value of the PersonId property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static Author CreateAuthor(global::System.Int32 personId, global::System.String lastName)
        {
            Author author = new Author();
            author.PersonId = personId;
            author.LastName = lastName;
            return author;
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "AuthorBook", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("Sweng500.Pml.DataAccessLayer.AuthorBook", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("Sweng500.Pml.DataAccessLayer.AuthorBook", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Book : Media
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Book object.
        /// </summary>
        /// <param name="mediaId">Initial value of the MediaId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="acquired">Initial value of the Acquired property.</param>
        /// <param name="isBorrowable">Initial value of the IsBorrowable property.</param>
        /// <param name="published">Initial value of the Published property.</param>
        public static Book CreateBook(global::System.Int32 mediaId, global::System.String title, global::System.DateTime acquired, global::System.Boolean isBorrowable, global::System.DateTime published)
        {
            Book book = new Book();
            book.MediaId = mediaId;
            book.Title = title;
            book.Acquired = acquired;
            book.IsBorrowable = isBorrowable;
            book.Published = published;
            return book;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LibraryLocation
        {
            get
            {
                return _LibraryLocation;
            }
            set
            {
                OnLibraryLocationChanging(value);
                ReportPropertyChanging("LibraryLocation");
                _LibraryLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LibraryLocation");
                OnLibraryLocationChanged();
            }
        }
        private global::System.String _LibraryLocation;
        partial void OnLibraryLocationChanging(global::System.String value);
        partial void OnLibraryLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Published
        {
            get
            {
                return _Published;
            }
            set
            {
                OnPublishedChanging(value);
                ReportPropertyChanging("Published");
                _Published = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Published");
                OnPublishedChanged();
            }
        }
        private global::System.DateTime _Published;
        partial void OnPublishedChanging(global::System.DateTime value);
        partial void OnPublishedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "AuthorBook", "Author")]
        public EntityCollection<Author> Authors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Author>("Sweng500.Pml.DataAccessLayer.AuthorBook", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Author>("Sweng500.Pml.DataAccessLayer.AuthorBook", "Author", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="BorrowedMedia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BorrowedMedia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BorrowedMedia object.
        /// </summary>
        /// <param name="borrowedOn">Initial value of the BorrowedOn property.</param>
        /// <param name="borrowerPersonId">Initial value of the BorrowerPersonId property.</param>
        /// <param name="mediaMediaId">Initial value of the MediaMediaId property.</param>
        /// <param name="borrowedMediaId">Initial value of the BorrowedMediaId property.</param>
        public static BorrowedMedia CreateBorrowedMedia(global::System.DateTime borrowedOn, global::System.Int32 borrowerPersonId, global::System.Int32 mediaMediaId, global::System.Int32 borrowedMediaId)
        {
            BorrowedMedia borrowedMedia = new BorrowedMedia();
            borrowedMedia.BorrowedOn = borrowedOn;
            borrowedMedia.BorrowerPersonId = borrowerPersonId;
            borrowedMedia.MediaMediaId = mediaMediaId;
            borrowedMedia.BorrowedMediaId = borrowedMediaId;
            return borrowedMedia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BorrowedOn
        {
            get
            {
                return _BorrowedOn;
            }
            set
            {
                OnBorrowedOnChanging(value);
                ReportPropertyChanging("BorrowedOn");
                _BorrowedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BorrowedOn");
                OnBorrowedOnChanged();
            }
        }
        private global::System.DateTime _BorrowedOn;
        partial void OnBorrowedOnChanging(global::System.DateTime value);
        partial void OnBorrowedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BorrowerPersonId
        {
            get
            {
                return _BorrowerPersonId;
            }
            set
            {
                OnBorrowerPersonIdChanging(value);
                ReportPropertyChanging("BorrowerPersonId");
                _BorrowerPersonId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BorrowerPersonId");
                OnBorrowerPersonIdChanged();
            }
        }
        private global::System.Int32 _BorrowerPersonId;
        partial void OnBorrowerPersonIdChanging(global::System.Int32 value);
        partial void OnBorrowerPersonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReturnedOn
        {
            get
            {
                return _ReturnedOn;
            }
            set
            {
                OnReturnedOnChanging(value);
                ReportPropertyChanging("ReturnedOn");
                _ReturnedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnedOn");
                OnReturnedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReturnedOn;
        partial void OnReturnedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnReturnedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaMediaId
        {
            get
            {
                return _MediaMediaId;
            }
            set
            {
                OnMediaMediaIdChanging(value);
                ReportPropertyChanging("MediaMediaId");
                _MediaMediaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MediaMediaId");
                OnMediaMediaIdChanged();
            }
        }
        private global::System.Int32 _MediaMediaId;
        partial void OnMediaMediaIdChanging(global::System.Int32 value);
        partial void OnMediaMediaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BorrowedMediaId
        {
            get
            {
                return _BorrowedMediaId;
            }
            set
            {
                if (_BorrowedMediaId != value)
                {
                    OnBorrowedMediaIdChanging(value);
                    ReportPropertyChanging("BorrowedMediaId");
                    _BorrowedMediaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BorrowedMediaId");
                    OnBorrowedMediaIdChanged();
                }
            }
        }
        private global::System.Int32 _BorrowedMediaId;
        partial void OnBorrowedMediaIdChanging(global::System.Int32 value);
        partial void OnBorrowedMediaIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "BorrowerBorrowedMedia", "Borrower")]
        public Borrower Borrower
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Borrower>("Sweng500.Pml.DataAccessLayer.BorrowerBorrowedMedia", "Borrower").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Borrower>("Sweng500.Pml.DataAccessLayer.BorrowerBorrowedMedia", "Borrower").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Borrower> BorrowerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Borrower>("Sweng500.Pml.DataAccessLayer.BorrowerBorrowedMedia", "Borrower");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Borrower>("Sweng500.Pml.DataAccessLayer.BorrowerBorrowedMedia", "Borrower", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "MediaBorrowedMedia", "Media")]
        public Media Media
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Media>("Sweng500.Pml.DataAccessLayer.MediaBorrowedMedia", "Media").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Media>("Sweng500.Pml.DataAccessLayer.MediaBorrowedMedia", "Media").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Media> MediaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Media>("Sweng500.Pml.DataAccessLayer.MediaBorrowedMedia", "Media");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Media>("Sweng500.Pml.DataAccessLayer.MediaBorrowedMedia", "Media", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Borrower")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Borrower : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Borrower object.
        /// </summary>
        /// <param name="personId">Initial value of the PersonId property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static Borrower CreateBorrower(global::System.Int32 personId, global::System.String lastName)
        {
            Borrower borrower = new Borrower();
            borrower.PersonId = personId;
            borrower.LastName = lastName;
            return borrower;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CanBorrow
        {
            get
            {
                return _CanBorrow;
            }
            set
            {
                OnCanBorrowChanging(value);
                ReportPropertyChanging("CanBorrow");
                _CanBorrow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanBorrow");
                OnCanBorrowChanged();
            }
        }
        private Nullable<global::System.Boolean> _CanBorrow;
        partial void OnCanBorrowChanging(Nullable<global::System.Boolean> value);
        partial void OnCanBorrowChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "BorrowerBorrowedMedia", "BorrowedMedia")]
        public EntityCollection<BorrowedMedia> BorrowedMedias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BorrowedMedia>("Sweng500.Pml.DataAccessLayer.BorrowerBorrowedMedia", "BorrowedMedia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BorrowedMedia>("Sweng500.Pml.DataAccessLayer.BorrowerBorrowedMedia", "BorrowedMedia", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Code")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Code : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Code object.
        /// </summary>
        /// <param name="codeId">Initial value of the CodeId property.</param>
        /// <param name="codeDescription">Initial value of the CodeDescription property.</param>
        /// <param name="codeTypeId">Initial value of the CodeTypeId property.</param>
        public static Code CreateCode(global::System.Int32 codeId, global::System.String codeDescription, global::System.Int32 codeTypeId)
        {
            Code code = new Code();
            code.CodeId = codeId;
            code.CodeDescription = codeDescription;
            code.CodeTypeId = codeTypeId;
            return code;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodeId
        {
            get
            {
                return _CodeId;
            }
            set
            {
                if (_CodeId != value)
                {
                    OnCodeIdChanging(value);
                    ReportPropertyChanging("CodeId");
                    _CodeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodeId");
                    OnCodeIdChanged();
                }
            }
        }
        private global::System.Int32 _CodeId;
        partial void OnCodeIdChanging(global::System.Int32 value);
        partial void OnCodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeDescription
        {
            get
            {
                return _CodeDescription;
            }
            set
            {
                OnCodeDescriptionChanging(value);
                ReportPropertyChanging("CodeDescription");
                _CodeDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeDescription");
                OnCodeDescriptionChanged();
            }
        }
        private global::System.String _CodeDescription;
        partial void OnCodeDescriptionChanging(global::System.String value);
        partial void OnCodeDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodeTypeId
        {
            get
            {
                return _CodeTypeId;
            }
            set
            {
                OnCodeTypeIdChanging(value);
                ReportPropertyChanging("CodeTypeId");
                _CodeTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodeTypeId");
                OnCodeTypeIdChanged();
            }
        }
        private global::System.Int32 _CodeTypeId;
        partial void OnCodeTypeIdChanging(global::System.Int32 value);
        partial void OnCodeTypeIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "CodeTypeCode", "CodeType")]
        public CodeType CodeType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodeType>("Sweng500.Pml.DataAccessLayer.CodeTypeCode", "CodeType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodeType>("Sweng500.Pml.DataAccessLayer.CodeTypeCode", "CodeType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CodeType> CodeTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodeType>("Sweng500.Pml.DataAccessLayer.CodeTypeCode", "CodeType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CodeType>("Sweng500.Pml.DataAccessLayer.CodeTypeCode", "CodeType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="CodeType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CodeType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CodeType object.
        /// </summary>
        /// <param name="codeTypeId">Initial value of the CodeTypeId property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static CodeType CreateCodeType(global::System.Int32 codeTypeId, global::System.String type)
        {
            CodeType codeType = new CodeType();
            codeType.CodeTypeId = codeTypeId;
            codeType.Type = type;
            return codeType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodeTypeId
        {
            get
            {
                return _CodeTypeId;
            }
            set
            {
                if (_CodeTypeId != value)
                {
                    OnCodeTypeIdChanging(value);
                    ReportPropertyChanging("CodeTypeId");
                    _CodeTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodeTypeId");
                    OnCodeTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _CodeTypeId;
        partial void OnCodeTypeIdChanging(global::System.Int32 value);
        partial void OnCodeTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "CodeTypeCode", "Code")]
        public EntityCollection<Code> Codes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Code>("Sweng500.Pml.DataAccessLayer.CodeTypeCode", "Code");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Code>("Sweng500.Pml.DataAccessLayer.CodeTypeCode", "Code", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Director")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Director : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Director object.
        /// </summary>
        /// <param name="personId">Initial value of the PersonId property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static Director CreateDirector(global::System.Int32 personId, global::System.String lastName)
        {
            Director director = new Director();
            director.PersonId = personId;
            director.LastName = lastName;
            return director;
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "DirectorVideo", "Video")]
        public EntityCollection<Video> Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Video>("Sweng500.Pml.DataAccessLayer.DirectorVideo", "Video");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Video>("Sweng500.Pml.DataAccessLayer.DirectorVideo", "Video", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Media")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Book))]
    [KnownTypeAttribute(typeof(Video))]
    public abstract partial class Media : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaId
        {
            get
            {
                return _MediaId;
            }
            set
            {
                if (_MediaId != value)
                {
                    OnMediaIdChanging(value);
                    ReportPropertyChanging("MediaId");
                    _MediaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MediaId");
                    OnMediaIdChanged();
                }
            }
        }
        private global::System.Int32 _MediaId;
        partial void OnMediaIdChanging(global::System.Int32 value);
        partial void OnMediaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Publisher
        {
            get
            {
                return _Publisher;
            }
            set
            {
                OnPublisherChanging(value);
                ReportPropertyChanging("Publisher");
                _Publisher = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Publisher");
                OnPublisherChanged();
            }
        }
        private global::System.String _Publisher;
        partial void OnPublisherChanging(global::System.String value);
        partial void OnPublisherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Acquired
        {
            get
            {
                return _Acquired;
            }
            set
            {
                OnAcquiredChanging(value);
                ReportPropertyChanging("Acquired");
                _Acquired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Acquired");
                OnAcquiredChanged();
            }
        }
        private global::System.DateTime _Acquired;
        partial void OnAcquiredChanging(global::System.DateTime value);
        partial void OnAcquiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NumberOfStars
        {
            get
            {
                return _NumberOfStars;
            }
            set
            {
                OnNumberOfStarsChanging(value);
                ReportPropertyChanging("NumberOfStars");
                _NumberOfStars = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfStars");
                OnNumberOfStarsChanged();
            }
        }
        private Nullable<global::System.Decimal> _NumberOfStars;
        partial void OnNumberOfStarsChanging(Nullable<global::System.Decimal> value);
        partial void OnNumberOfStarsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsBorrowable
        {
            get
            {
                return _IsBorrowable;
            }
            set
            {
                OnIsBorrowableChanging(value);
                ReportPropertyChanging("IsBorrowable");
                _IsBorrowable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBorrowable");
                OnIsBorrowableChanged();
            }
        }
        private global::System.Boolean _IsBorrowable;
        partial void OnIsBorrowableChanging(global::System.Boolean value);
        partial void OnIsBorrowableChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "MediaBorrowedMedia", "BorrowedMedia")]
        public EntityCollection<BorrowedMedia> BorrowedMedias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BorrowedMedia>("Sweng500.Pml.DataAccessLayer.MediaBorrowedMedia", "BorrowedMedia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BorrowedMedia>("Sweng500.Pml.DataAccessLayer.MediaBorrowedMedia", "BorrowedMedia", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Borrower))]
    [KnownTypeAttribute(typeof(Author))]
    [KnownTypeAttribute(typeof(Producer))]
    [KnownTypeAttribute(typeof(Director))]
    [KnownTypeAttribute(typeof(User))]
    public abstract partial class Person : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                if (_PersonId != value)
                {
                    OnPersonIdChanging(value);
                    ReportPropertyChanging("PersonId");
                    _PersonId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PersonId");
                    OnPersonIdChanged();
                }
            }
        }
        private global::System.Int32 _PersonId;
        partial void OnPersonIdChanging(global::System.Int32 value);
        partial void OnPersonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateOrProvince
        {
            get
            {
                return _StateOrProvince;
            }
            set
            {
                OnStateOrProvinceChanging(value);
                ReportPropertyChanging("StateOrProvince");
                _StateOrProvince = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateOrProvince");
                OnStateOrProvinceChanged();
            }
        }
        private global::System.String _StateOrProvince;
        partial void OnStateOrProvinceChanging(global::System.String value);
        partial void OnStateOrProvinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Producer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producer : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Producer object.
        /// </summary>
        /// <param name="personId">Initial value of the PersonId property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static Producer CreateProducer(global::System.Int32 personId, global::System.String lastName)
        {
            Producer producer = new Producer();
            producer.PersonId = personId;
            producer.LastName = lastName;
            return producer;
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "VideoProducer", "Video")]
        public EntityCollection<Video> Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Video>("Sweng500.Pml.DataAccessLayer.VideoProducer", "Video");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Video>("Sweng500.Pml.DataAccessLayer.VideoProducer", "Video", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="personId">Initial value of the PersonId property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="lastLogin">Initial value of the LastLogin property.</param>
        public static User CreateUser(global::System.Int32 personId, global::System.String lastName, global::System.String code, global::System.Byte[] password, global::System.DateTime lastLogin)
        {
            User user = new User();
            user.PersonId = personId;
            user.LastName = lastName;
            user.Code = code;
            user.Password = password;
            user.LastLogin = lastLogin;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Password
        {
            get
            {
                return StructuralObject.GetValidValue(_Password);
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.Byte[] _Password;
        partial void OnPasswordChanging(global::System.Byte[] value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private global::System.DateTime _LastLogin;
        partial void OnLastLoginChanging(global::System.DateTime value);
        partial void OnLastLoginChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Video")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Video : Media
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="mediaId">Initial value of the MediaId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="acquired">Initial value of the Acquired property.</param>
        /// <param name="isBorrowable">Initial value of the IsBorrowable property.</param>
        /// <param name="released">Initial value of the Released property.</param>
        public static Video CreateVideo(global::System.Int32 mediaId, global::System.String title, global::System.DateTime acquired, global::System.Boolean isBorrowable, global::System.DateTime released)
        {
            Video video = new Video();
            video.MediaId = mediaId;
            video.Title = title;
            video.Acquired = acquired;
            video.IsBorrowable = isBorrowable;
            video.Released = released;
            return video;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UPC
        {
            get
            {
                return _UPC;
            }
            set
            {
                OnUPCChanging(value);
                ReportPropertyChanging("UPC");
                _UPC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UPC");
                OnUPCChanged();
            }
        }
        private global::System.String _UPC;
        partial void OnUPCChanging(global::System.String value);
        partial void OnUPCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Released
        {
            get
            {
                return _Released;
            }
            set
            {
                OnReleasedChanging(value);
                ReportPropertyChanging("Released");
                _Released = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Released");
                OnReleasedChanged();
            }
        }
        private global::System.DateTime _Released;
        partial void OnReleasedChanging(global::System.DateTime value);
        partial void OnReleasedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BoardRatingId
        {
            get
            {
                return _BoardRatingId;
            }
            set
            {
                OnBoardRatingIdChanging(value);
                ReportPropertyChanging("BoardRatingId");
                _BoardRatingId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BoardRatingId");
                OnBoardRatingIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BoardRatingId;
        partial void OnBoardRatingIdChanging(Nullable<global::System.Int32> value);
        partial void OnBoardRatingIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "VideoProducer", "Producer")]
        public EntityCollection<Producer> Producers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Producer>("Sweng500.Pml.DataAccessLayer.VideoProducer", "Producer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Producer>("Sweng500.Pml.DataAccessLayer.VideoProducer", "Producer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sweng500.Pml.DataAccessLayer", "DirectorVideo", "Director")]
        public EntityCollection<Director> Directors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Director>("Sweng500.Pml.DataAccessLayer.DirectorVideo", "Director");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Director>("Sweng500.Pml.DataAccessLayer.DirectorVideo", "Director", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
