//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Sweng500.Pml.DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MasterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MasterEntities object using the connection string found in the 'MasterEntities' section of the application configuration file.
        /// </summary>
        public MasterEntities() : base("name=MasterEntities", "MasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MasterEntities object.
        /// </summary>
        public MasterEntities(string connectionString) : base(connectionString, "MasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MasterEntities object.
        /// </summary>
        public MasterEntities(EntityConnection connection) : base(connection, "MasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Code> Code
        {
            get
            {
                if ((_Code == null))
                {
                    _Code = base.CreateObjectSet<Code>("Code");
                }
                return _Code;
            }
        }
        private ObjectSet<Code> _Code;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CodeType> CodeType
        {
            get
            {
                if ((_CodeType == null))
                {
                    _CodeType = base.CreateObjectSet<CodeType>("CodeType");
                }
                return _CodeType;
            }
        }
        private ObjectSet<CodeType> _CodeType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Media> Media
        {
            get
            {
                if ((_Media == null))
                {
                    _Media = base.CreateObjectSet<Media>("Media");
                }
                return _Media;
            }
        }
        private ObjectSet<Media> _Media;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> Person
        {
            get
            {
                if ((_Person == null))
                {
                    _Person = base.CreateObjectSet<Person>("Person");
                }
                return _Person;
            }
        }
        private ObjectSet<Person> _Person;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Code EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCode(Code code)
        {
            base.AddObject("Code", code);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CodeType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCodeType(CodeType codeType)
        {
            base.AddObject("CodeType", codeType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Media EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedia(Media media)
        {
            base.AddObject("Media", media);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Person EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPerson(Person person)
        {
            base.AddObject("Person", person);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="personID">Initial value of the PersonID property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="authorID">Initial value of the AuthorID property.</param>
        /// <param name="bookId">Initial value of the BookId property.</param>
        public static Author CreateAuthor(global::System.Int32 personID, global::System.String lastName, global::System.Int32 authorID, global::System.Int32 bookId)
        {
            Author author = new Author();
            author.PersonID = personID;
            author.LastName = lastName;
            author.AuthorID = authorID;
            author.BookId = bookId;
            return author;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthorID
        {
            get
            {
                return _AuthorID;
            }
            set
            {
                OnAuthorIDChanging(value);
                ReportPropertyChanging("AuthorID");
                _AuthorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorID");
                OnAuthorIDChanged();
            }
        }
        private global::System.Int32 _AuthorID;
        partial void OnAuthorIDChanging(global::System.Int32 value);
        partial void OnAuthorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookId
        {
            get
            {
                return _BookId;
            }
            set
            {
                OnBookIdChanging(value);
                ReportPropertyChanging("BookId");
                _BookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookId");
                OnBookIdChanged();
            }
        }
        private global::System.Int32 _BookId;
        partial void OnBookIdChanging(global::System.Int32 value);
        partial void OnBookIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Book : Media
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Book object.
        /// </summary>
        /// <param name="mediaID">Initial value of the MediaID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="bookID">Initial value of the BookID property.</param>
        public static Book CreateBook(global::System.Int32 mediaID, global::System.String title, global::System.Int32 bookID)
        {
            Book book = new Book();
            book.MediaID = mediaID;
            book.Title = title;
            book.BookID = bookID;
            return book;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookID
        {
            get
            {
                return _BookID;
            }
            set
            {
                OnBookIDChanging(value);
                ReportPropertyChanging("BookID");
                _BookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookID");
                OnBookIDChanged();
            }
        }
        private global::System.Int32 _BookID;
        partial void OnBookIDChanging(global::System.Int32 value);
        partial void OnBookIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LibraryLocation
        {
            get
            {
                return _LibraryLocation;
            }
            set
            {
                OnLibraryLocationChanging(value);
                ReportPropertyChanging("LibraryLocation");
                _LibraryLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LibraryLocation");
                OnLibraryLocationChanged();
            }
        }
        private global::System.String _LibraryLocation;
        partial void OnLibraryLocationChanging(global::System.String value);
        partial void OnLibraryLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Code")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Code : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Code object.
        /// </summary>
        /// <param name="codeID">Initial value of the CodeID property.</param>
        /// <param name="codeDescription">Initial value of the CodeDescription property.</param>
        /// <param name="codeTypeID">Initial value of the CodeTypeID property.</param>
        public static Code CreateCode(global::System.Int32 codeID, global::System.String codeDescription, global::System.Int32 codeTypeID)
        {
            Code code = new Code();
            code.CodeID = codeID;
            code.CodeDescription = codeDescription;
            code.CodeTypeID = codeTypeID;
            return code;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodeID
        {
            get
            {
                return _CodeID;
            }
            set
            {
                if (_CodeID != value)
                {
                    OnCodeIDChanging(value);
                    ReportPropertyChanging("CodeID");
                    _CodeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodeID");
                    OnCodeIDChanged();
                }
            }
        }
        private global::System.Int32 _CodeID;
        partial void OnCodeIDChanging(global::System.Int32 value);
        partial void OnCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeDescription
        {
            get
            {
                return _CodeDescription;
            }
            set
            {
                OnCodeDescriptionChanging(value);
                ReportPropertyChanging("CodeDescription");
                _CodeDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeDescription");
                OnCodeDescriptionChanged();
            }
        }
        private global::System.String _CodeDescription;
        partial void OnCodeDescriptionChanging(global::System.String value);
        partial void OnCodeDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodeTypeID
        {
            get
            {
                return _CodeTypeID;
            }
            set
            {
                OnCodeTypeIDChanging(value);
                ReportPropertyChanging("CodeTypeID");
                _CodeTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodeTypeID");
                OnCodeTypeIDChanged();
            }
        }
        private global::System.Int32 _CodeTypeID;
        partial void OnCodeTypeIDChanging(global::System.Int32 value);
        partial void OnCodeTypeIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="CodeType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CodeType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CodeType object.
        /// </summary>
        /// <param name="codeTypeID">Initial value of the CodeTypeID property.</param>
        /// <param name="codeType1">Initial value of the CodeType1 property.</param>
        public static CodeType CreateCodeType(global::System.Int32 codeTypeID, global::System.String codeType1)
        {
            CodeType codeType = new CodeType();
            codeType.CodeTypeID = codeTypeID;
            codeType.CodeType1 = codeType1;
            return codeType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodeTypeID
        {
            get
            {
                return _CodeTypeID;
            }
            set
            {
                if (_CodeTypeID != value)
                {
                    OnCodeTypeIDChanging(value);
                    ReportPropertyChanging("CodeTypeID");
                    _CodeTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodeTypeID");
                    OnCodeTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _CodeTypeID;
        partial void OnCodeTypeIDChanging(global::System.Int32 value);
        partial void OnCodeTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeType1
        {
            get
            {
                return _CodeType1;
            }
            set
            {
                OnCodeType1Changing(value);
                ReportPropertyChanging("CodeType1");
                _CodeType1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeType1");
                OnCodeType1Changed();
            }
        }
        private global::System.String _CodeType1;
        partial void OnCodeType1Changing(global::System.String value);
        partial void OnCodeType1Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Media")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Book))]
    [KnownTypeAttribute(typeof(Video))]
    public abstract partial class Media : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaID
        {
            get
            {
                return _MediaID;
            }
            set
            {
                if (_MediaID != value)
                {
                    OnMediaIDChanging(value);
                    ReportPropertyChanging("MediaID");
                    _MediaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MediaID");
                    OnMediaIDChanged();
                }
            }
        }
        private global::System.Int32 _MediaID;
        partial void OnMediaIDChanging(global::System.Int32 value);
        partial void OnMediaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Publisher
        {
            get
            {
                return _Publisher;
            }
            set
            {
                OnPublisherChanging(value);
                ReportPropertyChanging("Publisher");
                _Publisher = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Publisher");
                OnPublisherChanged();
            }
        }
        private global::System.String _Publisher;
        partial void OnPublisherChanging(global::System.String value);
        partial void OnPublisherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Published
        {
            get
            {
                return _Published;
            }
            set
            {
                OnPublishedChanging(value);
                ReportPropertyChanging("Published");
                _Published = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Published");
                OnPublishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Published;
        partial void OnPublishedChanging(Nullable<global::System.DateTime> value);
        partial void OnPublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GenreID
        {
            get
            {
                return _GenreID;
            }
            set
            {
                OnGenreIDChanging(value);
                ReportPropertyChanging("GenreID");
                _GenreID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenreID");
                OnGenreIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GenreID;
        partial void OnGenreIDChanging(Nullable<global::System.Int32> value);
        partial void OnGenreIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FormatID
        {
            get
            {
                return _FormatID;
            }
            set
            {
                OnFormatIDChanging(value);
                ReportPropertyChanging("FormatID");
                _FormatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormatID");
                OnFormatIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FormatID;
        partial void OnFormatIDChanging(Nullable<global::System.Int32> value);
        partial void OnFormatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Acquired
        {
            get
            {
                return _Acquired;
            }
            set
            {
                OnAcquiredChanging(value);
                ReportPropertyChanging("Acquired");
                _Acquired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Acquired");
                OnAcquiredChanged();
            }
        }
        private Nullable<global::System.DateTime> _Acquired;
        partial void OnAcquiredChanging(Nullable<global::System.DateTime> value);
        partial void OnAcquiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsBorrowable
        {
            get
            {
                return _IsBorrowable;
            }
            set
            {
                OnIsBorrowableChanging(value);
                ReportPropertyChanging("IsBorrowable");
                _IsBorrowable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBorrowable");
                OnIsBorrowableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsBorrowable;
        partial void OnIsBorrowableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsBorrowableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsBorrowed
        {
            get
            {
                return _IsBorrowed;
            }
            set
            {
                OnIsBorrowedChanging(value);
                ReportPropertyChanging("IsBorrowed");
                _IsBorrowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBorrowed");
                OnIsBorrowedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsBorrowed;
        partial void OnIsBorrowedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsBorrowedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BorrowerID
        {
            get
            {
                return _BorrowerID;
            }
            set
            {
                OnBorrowerIDChanging(value);
                ReportPropertyChanging("BorrowerID");
                _BorrowerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BorrowerID");
                OnBorrowerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BorrowerID;
        partial void OnBorrowerIDChanging(Nullable<global::System.Int32> value);
        partial void OnBorrowerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NumOfStars
        {
            get
            {
                return _NumOfStars;
            }
            set
            {
                OnNumOfStarsChanging(value);
                ReportPropertyChanging("NumOfStars");
                _NumOfStars = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumOfStars");
                OnNumOfStarsChanged();
            }
        }
        private Nullable<global::System.Decimal> _NumOfStars;
        partial void OnNumOfStarsChanging(Nullable<global::System.Decimal> value);
        partial void OnNumOfStarsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MediaDescription
        {
            get
            {
                return _MediaDescription;
            }
            set
            {
                OnMediaDescriptionChanging(value);
                ReportPropertyChanging("MediaDescription");
                _MediaDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MediaDescription");
                OnMediaDescriptionChanged();
            }
        }
        private global::System.String _MediaDescription;
        partial void OnMediaDescriptionChanging(global::System.String value);
        partial void OnMediaDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Author))]
    [KnownTypeAttribute(typeof(ProducerDirector))]
    [KnownTypeAttribute(typeof(User))]
    public abstract partial class Person : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonID
        {
            get
            {
                return _PersonID;
            }
            set
            {
                if (_PersonID != value)
                {
                    OnPersonIDChanging(value);
                    ReportPropertyChanging("PersonID");
                    _PersonID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PersonID");
                    OnPersonIDChanged();
                }
            }
        }
        private global::System.Int32 _PersonID;
        partial void OnPersonIDChanging(global::System.Int32 value);
        partial void OnPersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateProvence
        {
            get
            {
                return _StateProvence;
            }
            set
            {
                OnStateProvenceChanging(value);
                ReportPropertyChanging("StateProvence");
                _StateProvence = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateProvence");
                OnStateProvenceChanged();
            }
        }
        private global::System.String _StateProvence;
        partial void OnStateProvenceChanging(global::System.String value);
        partial void OnStateProvenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="ProducerDirector")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProducerDirector : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProducerDirector object.
        /// </summary>
        /// <param name="personID">Initial value of the PersonID property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="producerDirectorID">Initial value of the ProducerDirectorID property.</param>
        /// <param name="videoID">Initial value of the VideoID property.</param>
        /// <param name="isProducer">Initial value of the IsProducer property.</param>
        public static ProducerDirector CreateProducerDirector(global::System.Int32 personID, global::System.String lastName, global::System.Int32 producerDirectorID, global::System.Int32 videoID, global::System.Boolean isProducer)
        {
            ProducerDirector producerDirector = new ProducerDirector();
            producerDirector.PersonID = personID;
            producerDirector.LastName = lastName;
            producerDirector.ProducerDirectorID = producerDirectorID;
            producerDirector.VideoID = videoID;
            producerDirector.IsProducer = isProducer;
            return producerDirector;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProducerDirectorID
        {
            get
            {
                return _ProducerDirectorID;
            }
            set
            {
                OnProducerDirectorIDChanging(value);
                ReportPropertyChanging("ProducerDirectorID");
                _ProducerDirectorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProducerDirectorID");
                OnProducerDirectorIDChanged();
            }
        }
        private global::System.Int32 _ProducerDirectorID;
        partial void OnProducerDirectorIDChanging(global::System.Int32 value);
        partial void OnProducerDirectorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VideoID
        {
            get
            {
                return _VideoID;
            }
            set
            {
                OnVideoIDChanging(value);
                ReportPropertyChanging("VideoID");
                _VideoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VideoID");
                OnVideoIDChanged();
            }
        }
        private global::System.Int32 _VideoID;
        partial void OnVideoIDChanging(global::System.Int32 value);
        partial void OnVideoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsProducer
        {
            get
            {
                return _IsProducer;
            }
            set
            {
                OnIsProducerChanging(value);
                ReportPropertyChanging("IsProducer");
                _IsProducer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsProducer");
                OnIsProducerChanged();
            }
        }
        private global::System.Boolean _IsProducer;
        partial void OnIsProducerChanging(global::System.Boolean value);
        partial void OnIsProducerChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : Person
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="personID">Initial value of the PersonID property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="userCode">Initial value of the UserCode property.</param>
        /// <param name="passwordHash">Initial value of the PasswordHash property.</param>
        public static User CreateUser(global::System.Int32 personID, global::System.String lastName, global::System.Int32 userID, global::System.String userCode, global::System.Byte[] passwordHash)
        {
            User user = new User();
            user.PersonID = personID;
            user.LastName = lastName;
            user.UserID = userID;
            user.UserCode = userCode;
            user.PasswordHash = passwordHash;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserCode
        {
            get
            {
                return _UserCode;
            }
            set
            {
                OnUserCodeChanging(value);
                ReportPropertyChanging("UserCode");
                _UserCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserCode");
                OnUserCodeChanged();
            }
        }
        private global::System.String _UserCode;
        partial void OnUserCodeChanging(global::System.String value);
        partial void OnUserCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] PasswordHash
        {
            get
            {
                return StructuralObject.GetValidValue(_PasswordHash);
            }
            set
            {
                OnPasswordHashChanging(value);
                ReportPropertyChanging("PasswordHash");
                _PasswordHash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PasswordHash");
                OnPasswordHashChanged();
            }
        }
        private global::System.Byte[] _PasswordHash;
        partial void OnPasswordHashChanging(global::System.Byte[] value);
        partial void OnPasswordHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogindatetime
        {
            get
            {
                return _LastLogindatetime;
            }
            set
            {
                OnLastLogindatetimeChanging(value);
                ReportPropertyChanging("LastLogindatetime");
                _LastLogindatetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogindatetime");
                OnLastLogindatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogindatetime;
        partial void OnLastLogindatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLogindatetimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sweng500.Pml.DataAccessLayer", Name="Video")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Video : Media
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="mediaID">Initial value of the MediaID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="videoID">Initial value of the VideoID property.</param>
        public static Video CreateVideo(global::System.Int32 mediaID, global::System.String title, global::System.Int32 videoID)
        {
            Video video = new Video();
            video.MediaID = mediaID;
            video.Title = title;
            video.VideoID = videoID;
            return video;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VideoID
        {
            get
            {
                return _VideoID;
            }
            set
            {
                OnVideoIDChanging(value);
                ReportPropertyChanging("VideoID");
                _VideoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VideoID");
                OnVideoIDChanged();
            }
        }
        private global::System.Int32 _VideoID;
        partial void OnVideoIDChanging(global::System.Int32 value);
        partial void OnVideoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Released
        {
            get
            {
                return _Released;
            }
            set
            {
                OnReleasedChanging(value);
                ReportPropertyChanging("Released");
                _Released = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Released");
                OnReleasedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Released;
        partial void OnReleasedChanging(Nullable<global::System.DateTime> value);
        partial void OnReleasedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BoardRatingID
        {
            get
            {
                return _BoardRatingID;
            }
            set
            {
                OnBoardRatingIDChanging(value);
                ReportPropertyChanging("BoardRatingID");
                _BoardRatingID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BoardRatingID");
                OnBoardRatingIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BoardRatingID;
        partial void OnBoardRatingIDChanging(Nullable<global::System.Int32> value);
        partial void OnBoardRatingIDChanged();

        #endregion
    
    }

    #endregion
    
}
